ADD: DetailView
wecode-bootcamp-korea/24-2nd-FLIP-backend pull request #13
Opened 2021-09-16 14:37 UTC by sdk1926

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-17 06:22 UTC, jamessoun93 requested changes

2021-09-17 06:22 UTC, jamessoun93 commented on products/views.py
> +        return JsonResponse({'result':result}, status=200)
- 의도는 잘 파악했으나 `is_liked` 를 보여줄지 말지 여부때문에 이렇게 많은 줄의 코드와 로직이 반복되는 것은 무조건 지양하셔야 합니다. 
- 이런식으로 나누는 것 보다, `http headers` 의 `authorization token` 유무를 판단하여 '좋아요' 여부만 확인시켜주는 기능을 따로 만들어서 호출을 하시거나, 로그인을 안한 유저는 무조건 `is_liked` 의 값이 `False` 이기때문에 `False` 로 통일시켜주시는 방법도 있습니다.

2021-09-17 06:56 UTC, sdk1926 commented on products/views.py
> +        return JsonResponse({'result':result}, status=200)
네 알겠습니다!

2021-09-17 08:55 UTC, jamessoun93 commented
푸시하실때 conflict 같이 해결해주세요!

2021-09-27 01:13 UTC, jamessoun93 approved these changes

2021-09-27 01:13 UTC, merged