ADD:ReviewView
wecode-bootcamp-korea/24-2nd-FLIP-backend pull request #18
Opened 2021-09-24 10:11 UTC by sdk1926

>wecode PR message template 및 체크 리스트 입니다. 

## 수정 사항 간략한 한줄 요약
- 리뷰 조회기능 구현 
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-27 06:31 UTC, jamessoun93 commented
이전 pr 과 같은 내용들이 있는것 같아서 rebase 한번 해서 conflict 싹 정리해서 올려주신 다음 확인하겠습니다.

2021-09-27 15:11 UTC, jamessoun93 requested changes

2021-09-27 15:11 UTC, jamessoun93 commented on products/views.py
> +
불필요한 빈줄입니다.

2021-09-27 15:11 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({'MESSAGE' : 'NOT_FOUND'}, status=404)
존재하지 않는 product 에 대한 review get 요청이니 메세지도 명확하게 `PRODUCT NOT FOUND` <- 이런식으로 변경해주세요.

2021-09-28 00:21 UTC, sdk1926 commented on products/views.py
> +
네 반영했습니다.

2021-09-28 00:21 UTC, sdk1926 commented on products/views.py
> +            return JsonResponse({'MESSAGE' : 'NOT_FOUND'}, status=404)
변경했습니다.

2021-09-28 01:11 UTC, merged