[손명희]Add:UserProductView
wecode-bootcamp-korea/24-2nd-FLIP-backend pull request #19
Opened 2021-09-26 11:18 UTC by melody-story

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 계좌가 등록된 유저의 상품등록 및 조회 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- NA

## 기타 질문 및 특이 사항

1. 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.
2. S3에 이미지 파일 등록에 관한 유닛 테스트 구현시 카카오 소셜 로그인과 같이 mock response를 구현하면되는지 문의드립니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-28 07:00 UTC, jamessoun93 requested changes

2021-09-28 07:00 UTC, jamessoun93 commented on products/views.py
> +            ) for image in image_list]
이 부분은 transaction 이 필요합니다. 적용해주세요!

2021-09-28 13:22 UTC, melody-story commented on products/views.py
> +            ) for image in image_list]
save포인트가 따로 필요하지 않는 것으로 생각되어 전체 코드 transaction 처리하였으며 리뷰 요청드립니다. @jamessoun93

2021-09-29 02:12 UTC, jamessoun93 approved these changes

2021-09-29 02:12 UTC, merged