[24기 성우진] Main Page Category View
wecode-bootcamp-korea/24-2nd-FLIP-backend pull request #21
Opened 2021-09-27 04:29 UTC by jinatra

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 메인 페이지의 메인 카테고리 아이콘 데이터 API
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
- 별도의 요청 없이 url만 주는 API의 경우에 잡아야 할 에러가 있을까요? 
   에러 뜰 게 없을 거 같은데.. 또 있을거 같기도 하고 헷갈립니다. (그래서 예외처리를 하지 않았습니다)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-28 12:43 UTC, jamessoun93 requested changes

2021-09-28 12:43 UTC, jamessoun93 commented on products/views.py
> +from unittest.main import main
views.py에 unittest.main 이 들어가는 이유가 있을까요? 없애주세요~

2021-09-28 12:44 UTC, jamessoun93 commented
> 별도의 요청 없이 url만 주는 API의 경우에 잡아야 할 에러가 있을까요?
에러 뜰 게 없을 거 같은데.. 또 있을거 같기도 하고 헷갈립니다. (그래서 예외처리를 하지 않았습니다)

꼭 FAIL 케이스가 있어야하는 것은 아닙니다. 그런데 별도의 요청 없이 url 만 주는 API라는게 무슨뜻일까요?

2021-09-29 01:20 UTC, jinatra commented on products/views.py
> +from unittest.main import main
VC에서 자동으로 추가된것 같습니다
삭제했습니다!

2021-09-29 01:24 UTC, jinatra commented
> > 별도의 요청 없이 url만 주는 API의 경우에 잡아야 할 에러가 있을까요?
> > 에러 뜰 게 없을 거 같은데.. 또 있을거 같기도 하고 헷갈립니다. (그래서 예외처리를 하지 않았습니다)
> 
> 꼭 FAIL 케이스가 있어야하는 것은 아닙니다. 그런데 별도의 요청 없이 url 만 주는 API라는게 무슨뜻일까요?



> > 별도의 요청 없이 url만 주는 API의 경우에 잡아야 할 에러가 있을까요?
> > 에러 뜰 게 없을 거 같은데.. 또 있을거 같기도 하고 헷갈립니다. (그래서 예외처리를 하지 않았습니다)
> 
> 꼭 FAIL 케이스가 있어야하는 것은 아닙니다. 그런데 별도의 요청 없이 url 만 주는 API라는게 무슨뜻일까요?


그동안은 프론트엔드와 path 파라미터나 query 파라미터를 통해 데이터의 상호교류가 있었는데 이번에는 그냥 백엔드에서 정해진 데이터를 보내주기만 하는 상황이라서, 이런 경우도 있는게 흔한지 여쭤보고 싶었습니다.

2021-09-29 02:16 UTC, jamessoun93 commented
> 그동안은 프론트엔드와 path 파라미터나 query 파라미터를 통해 데이터의 상호교류가 있었는데 이번에는 그냥 백엔드에서 정해진 데이터를 보내주기만 하는 상황이라서, 이런 경우도 있는게 흔한지 여쭤보고 싶었습니다.

넵넵 물론입니다!

2021-09-29 05:51 UTC, jamessoun93 approved these changes

2021-09-29 05:51 UTC, merged